<aside class="people col col-sm-5 col-md-4 col-md-offset-1" itemscope itemtype="http://schema.org/Organization">
    <div class="row">
        <figure class="col col-xs-12">
            <img src="<?=BASEURL?>/img/people/team.jpg"/>
        </figure>
        <figcaption>
            <span class="col col-xs-4 text-center">Vanessa<br/>Larrère</span>
            <span class="col col-xs-4 text-center">Claire<br/>Furlan</span>
            <span class="col col-xs-4 text-center">Coralie<br/>Bouscal</span>
        </figcaption>
    </div>

    <h2 itemprop="name">ŒCO Architectes</h2>

    <h3>Adresse</h3>
    <p itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <a href="https://www.google.fr/maps/place/31+Rue+Bertrand+de+Born,+31000+Toulouse/" target="_blank">
            <span itemprop="streetAddress">31 Rue Bertrand de Born</span>,<br />
            <span itemprop="postalCode">31000</span>
            <span itemprop="addressLocality">Toulouse</span><br />
        </a>
    </p>

    <h3>Téléphone</h3>
    <p class="telephone" itemprop="phone"><a href="tel:+33531989842">+33 (0)5 31 98 98 42</a></p>
    <p class="telephone" itemprop="phone"><a href="tel:+33671300261">+33 (0)6 71 30 02 61</a></p>

    <h3>Adresse électronique</h3>
    <p>
        <a href="mailto:agence@oeco-architectes.com" itemprop="email">agence@oeco-architectes.com</a>
    </p>

    <span id="geolocalisation" itemprop="geo" itemscope itemtype="http://data-vocabulary.org/Geo">
        Coordonnées GPS:
        <span itemprop="latitude">43.610269</span>,
        <span itemprop="longitude">1.452573</span>
    </span>
</aside>
