<script src="<?=BASEURL?>/js/jquery-1.12.4<?=MIN?>.js"></script>
<script src="<?=BASEURL?>/js/bootstrap<?=MIN?>.js"></script>
<script src="<?=BASEURL?>/js/website<?=MIN?>.js"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33132122-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = '<?=BASEURL?>/js/ga<?=MIN?>.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
