language: php
php:
  - 7.2
addons:
  chrome: stable
env:
  - COMPOSER_NO_INTERACTION=1
install:
  - travis_retry composer create-project --prefer-dist
before_script:
  - composer lint
  - php artisan serve & # Laravel Dusk
script:
  - composer test
after_script:
  - killall php
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
