language: php
php:
  - 7.2
env:
  - COMPOSER_NO_INTERACTION=1
install:
  - travis_retry composer create-project --prefer-dist
before_script:
  - composer lint
script:
  - composer test
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
