language: php
php:
  - 7.0
before_install:
  - git config core.safecrlf false
install:
  - travis_retry composer create-project --no-interaction
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - yarn run development
  - php artisan serve --env=testing &
script:
  - composer lint
  - composer test
  - composer e2e
  - killall chromedriver-linux
  - killall php
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
