<div class="row">
  <figure class="image col-sm-12">
    <a href="#<?=$image['id']?>" data-toggle="lightbox">
      <img src="<?=BASEURL?>/services/image.php?path=<?=$image['path']?>&amp;width=<?=$width?>" width="<?=$width?>" alt="<?=$image['legend']?>" title="<?=$image['legend']?>" />
    </a>
    <?php if(isset($image['legend'])): ?>
      <figcaption>
        <p><?=$image['legend']?></p>
      </figcaption>
    <?php endif; ?>

    <?php // Lightbox
    /*
    <div id="<?=$image['id']?>" class="lightbox fade" tabindex="-1" role="dialog" aria-hidden="true">
      <div class='lightbox-dialog'>
        <div class='lightbox-content'>
          <img src="<?=BASEURL?>/services/image.php?path=<?=$image['path']?>">
          <?php if(isset($image['legend'])): ?>
            <div class="lightbox-caption"><p><?=$image['legend']?></p></div>
          <?php endif; ?>
        </div>
      </div>
    </div>
    */
    ?>
  </figure>
</div>
