#!/usr/bin/env bash


# Post-deployment script
# ======================
#
# Downloads Composer (composer.phar) and run `install` (with `--no-dev`), `migrate` and `optimize`
# scripts.
#
# Usage
# -----
#
#     scripts/post-deploy
#
# Requirements
# ------------
#
# - PHP
# - curl

set -o errexit
set -o pipefail
set -o nounset

echo Starting post-deployment script...

# Check current directory
echo Current directory: "$PWD"
if [ ! -e composer.json ]
then
    echo Could not find composer.json, aborting... >&2
    exit 1
fi

# Check php version
if ! command -v php >/dev/null
then
    echo Could not execute php, aborting... >&2
    exit 1
fi
echo PHP version: "$(php -v | head -n 1)"

# Check .env file
if [ ! -e .env ]
then
    echo Could not find .env, aborting... >&2
    exit 1
fi

# Composer
if [ -e composer.phar ]
then
    echo Found composer.phar, running self-update...
    php composer.phar self-update
else
    echo Could not find composer.phar, downloading...
    curl -s https://getcomposer.org/installer | php
fi

# Installation
export COMPOSER_NO_INTERACTION=1
php composer.phar install --no-dev
php composer.phar migrate
php composer.phar optimize

echo Terminated post-deployment script successfully!
